### ISSUE TITLE
Console mistake. Uncaught Error: draganddrop component not found. Is it installed and included?

### ISSUE THREAD

**Issue by punkernow** [danielstorey/adapt-draganddrop#10]
Hello! Great component, but I can't use it. When page is loading, there are mistake in console:
![image](https://user-images.githubusercontent.com/31541909/29972299-691e99fa-8f34-11e7-8543-830ac2bef8db.png)

I use Adapt Authoring tool.
Could you help me for it?
Thanks

**Comment by danielstorey** [comment]
Hi please use "adapt-dragndrop" instead. I need to remove this repository.

Thanks and enjoy :)

**Comment by punkernow** [comment]
thanks a lot, it works great!!!

**Comment by danielstorey** [comment]
Cool!
