### ISSUE TITLE
If I add more than 1 attempt you can no longer drag and drop the boxes

### ISSUE THREAD

**Issue by mike-st** [danielstorey/adapt-draganddrop#7]
If I add more than 1 attempt you can no longer drag and drop the boxes

**Comment by kyuz0** [comment]
I confirm I'm having the same issue. Is anybody able to look into this? My JavaScript is terrible, but I suspect it's got to do with the library used to implement the drag/drop functionality not resetting events properly.

**Comment by kyuz0** [comment]
I have fixed this by adding this line at the end of _onResetClicked()_:

`this.$('.draganddrop-answers').children().draggable('enable');`

**Comment by mike-st** [comment]
Thanks worked like a charm!
