### ISSUE TITLE
Correct items not tracking properly

### ISSUE THREAD

**Issue by kmcmurphy** [danielstorey/adapt-draganddrop#8]
Correct answers show 'X' when properly matched. If a second correct answer is added, then it tracks properly.

![screen shot 2017-02-09 at 9 39 51 am](https://cloud.githubusercontent.com/assets/7529880/22790426/c7b5ca44-eeab-11e6-8396-f757bee3c3ee.png)

**Comment by danielstorey** [comment]
I don't seem to be able to replicate this. Does it always fail, or when you place the answers in a certain order, or on a retry etc?

**Comment by kmcmurphy** [comment]
It always happens, no matter which order the answers are placed in. I just made a new one in a different course and it behaves the same way on preview.

**Comment by mike-st** [comment]
KmCMurphy is right I am getting the same error I only have three answers for 2 questions and the first one is right therefore the second should be too cause there are no more answers to drag from. Here is a screen shot of the error with the script error in inspector too. Oddly this use to work maybe a new update that went wrong in the javascript file.

<img width="2552" alt="screen shot 2017-03-03 at 8 16 27 am" src="https://cloud.githubusercontent.com/assets/10455453/23552500/46987ee8-ffea-11e6-876a-2732f487627c.png">

**Comment by mike-st** [comment]
Hi Solved this issue. Under the markAnswers:function() Make this fix below...

markAnswers: function() {
			var numberOfCorrectAnswers = 0;
			this.model.set('_isAtLeastOneCorrectSelection', false);
			_.each(this.model.get('_items'), function(item) {
				if (typeof item.accepted === "string") {
					item._isCorrect = item.accepted === item._userAnswer;
				}
				else if (item.accepted.length === 1) { // if array of single value
					`item._isCorrect = item.accepted.sort().join() === item._userAnswer;`
				} else {
					item._isCorrect = item.accepted.sort().join() === item._userAnswer.sort().join();
				}

**Comment by danielstorey** [comment]
This should be sorted now. I am however no longer supporting this version due to to naming conflicts with existing Adapt plugins. Please see adapt-dragndrop instead!
