### ISSUE TITLE
Issue with Show/Hide Correct Answer Button 

### ISSUE THREAD

**Issue by mike-st** [danielstorey/adapt-draganddrop#9]
Hi I am having an issue with the Show/Hide Correct Answer button. After I have placed all the drag items in the wrong order on the final attempt and hit submit. I try clicking on the Show Correct Answer button which is located where the submit button use to be. There is an error popping up when I click it the correct anwsers are not dragging into place for me to see the right answer. Here is the error I am getting in inspector.. 

<img width="2231" alt="screen shot 2017-03-06 at 8 34 47 am" src="https://cloud.githubusercontent.com/assets/10455453/23612087/0456a6d0-0248-11e7-9c7f-f3110de91271.png">

**Comment by danielstorey** [comment]
This should be sorted now. I am however no longer supporting this version due to to naming conflicts with existing Adapt plugins. Please see adapt-dragndrop instead!
